In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.DataFrame(np.random.rand(50,4)) 
df

           0         1         2         3
0   0.957947  0.329723  0.573323  0.068723
1   0.970251  0.534354  0.371192  0.984706
2   0.181686  0.636601  0.775055  0.541684
3   0.282626  0.706310  0.843035  0.807849
4   0.916001  0.870574  0.953732  0.327281
5   0.469337  0.473610  0.187827  0.779300
6   0.723460  0.377932  0.673378  0.934733
7   0.903760  0.229099  0.831583  0.015014
8   0.780017  0.496608  0.139210  0.941163
9   0.074794  0.811899  0.089173  0.563264
10  0.760997  0.869896  0.436472  0.794498
11  0.712082  0.626183  0.151731  0.392466
12  0.718635  0.321063  0.063989  0.282076
13  0.383215  0.847225  0.446602  0.630955
14  0.982769  0.875104  0.403820  0.990278
15  0.982311  0.374351  0.784332  0.856525
16  0.763839  0.939116  0.404821  0.552194
17  0.022347  0.630668  0.489573  0.260511
18  0.627586  0.433779  0.671155  0.532874
19  0.301858  0.298769  0.798762  0.764259
20  0.142179  0.619653  0.323978  0.888950
21  0.926242  0.217204  0.564809  0.028075
22  0.179773  0.788458  0.029599  0.652266
23  0.171783  0.989442  0.937884  0.180094
24  0.208744  0.337994  0.302842  0.238919
25  0.926770  0.309315  0.494531  0.915049
26  0.055591  0.420022  0.188748  0.451578
27  0.632032  0.247067  0.957822  0.189549
28  0.562152  0.734134  0.497345  0.800104
29  0.579877  0.346681  0.854146  0.085848
30  0.211561  0.320044  0.943333  0.316814
31  0.097076  0.280410  0.772864  0.661712
32  0.974969  0.602378  0.940926  0.454194
33  0.423371  0.347027  0.756002  0.665183
34  0.932267  0.107655  0.750186  0.861590
35  0.861419  0.341958  0.370188  0.391162
36  0.473516  0.626241  0.895984  0.664134
37  0.717528  0.035882  0.331638  0.089512
38  0.436924  0.738777  0.235961  0.143661
39  0.419629  0.306565  0.922235  0.689459
40  0.921927  0.906192  0.317434  0.716091
41  0.398761  0.647721  0.184611  0.918044
42  0.265096  0.838655  0.705364  0.363530
43  0.788504  0.101992  0.046296  0.651167
44  0.889600  0.766079  0.661138  0.942407
45  0.810314  0.584719  0.497017  0.393669
46  0.770551  0.655027  0.197000  0.359072
47  0.059326  0.766461  0.077826  0.026166
48  0.321085  0.595879  0.931095  0.170308
49  0.600603  0.321105  0.973736  0.979337

In [3]:
df.columns = list("ABCD")

In [4]:
df

           A         B         C         D
0   0.957947  0.329723  0.573323  0.068723
1   0.970251  0.534354  0.371192  0.984706
2   0.181686  0.636601  0.775055  0.541684
3   0.282626  0.706310  0.843035  0.807849
4   0.916001  0.870574  0.953732  0.327281
5   0.469337  0.473610  0.187827  0.779300
6   0.723460  0.377932  0.673378  0.934733
7   0.903760  0.229099  0.831583  0.015014
8   0.780017  0.496608  0.139210  0.941163
9   0.074794  0.811899  0.089173  0.563264
10  0.760997  0.869896  0.436472  0.794498
11  0.712082  0.626183  0.151731  0.392466
12  0.718635  0.321063  0.063989  0.282076
13  0.383215  0.847225  0.446602  0.630955
14  0.982769  0.875104  0.403820  0.990278
15  0.982311  0.374351  0.784332  0.856525
16  0.763839  0.939116  0.404821  0.552194
17  0.022347  0.630668  0.489573  0.260511
18  0.627586  0.433779  0.671155  0.532874
19  0.301858  0.298769  0.798762  0.764259
20  0.142179  0.619653  0.323978  0.888950
21  0.926242  0.217204  0.564809  0.028075
22  0.179773  0.788458  0.029599  0.652266
23  0.171783  0.989442  0.937884  0.180094
24  0.208744  0.337994  0.302842  0.238919
25  0.926770  0.309315  0.494531  0.915049
26  0.055591  0.420022  0.188748  0.451578
27  0.632032  0.247067  0.957822  0.189549
28  0.562152  0.734134  0.497345  0.800104
29  0.579877  0.346681  0.854146  0.085848
30  0.211561  0.320044  0.943333  0.316814
31  0.097076  0.280410  0.772864  0.661712
32  0.974969  0.602378  0.940926  0.454194
33  0.423371  0.347027  0.756002  0.665183
34  0.932267  0.107655  0.750186  0.861590
35  0.861419  0.341958  0.370188  0.391162
36  0.473516  0.626241  0.895984  0.664134
37  0.717528  0.035882  0.331638  0.089512
38  0.436924  0.738777  0.235961  0.143661
39  0.419629  0.306565  0.922235  0.689459
40  0.921927  0.906192  0.317434  0.716091
41  0.398761  0.647721  0.184611  0.918044
42  0.265096  0.838655  0.705364  0.363530
43  0.788504  0.101992  0.046296  0.651167
44  0.889600  0.766079  0.661138  0.942407
45  0.810314  0.584719  0.497017  0.393669
46  0.770551  0.655027  0.197000  0.359072
47  0.059326  0.766461  0.077826  0.026166
48  0.321085  0.595879  0.931095  0.170308
49  0.600603  0.321105  0.973736  0.979337

# now we remove the data

In [5]:
df.head()

          A         B         C         D
0  0.957947  0.329723  0.573323  0.068723
1  0.970251  0.534354  0.371192  0.984706
2  0.181686  0.636601  0.775055  0.541684
3  0.282626  0.706310  0.843035  0.807849
4  0.916001  0.870574  0.953732  0.327281

In [6]:
df.drop(2,axis = 0)   # drop horizontally

           A         B         C         D
0   0.957947  0.329723  0.573323  0.068723
1   0.970251  0.534354  0.371192  0.984706
3   0.282626  0.706310  0.843035  0.807849
4   0.916001  0.870574  0.953732  0.327281
5   0.469337  0.473610  0.187827  0.779300
6   0.723460  0.377932  0.673378  0.934733
7   0.903760  0.229099  0.831583  0.015014
8   0.780017  0.496608  0.139210  0.941163
9   0.074794  0.811899  0.089173  0.563264
10  0.760997  0.869896  0.436472  0.794498
11  0.712082  0.626183  0.151731  0.392466
12  0.718635  0.321063  0.063989  0.282076
13  0.383215  0.847225  0.446602  0.630955
14  0.982769  0.875104  0.403820  0.990278
15  0.982311  0.374351  0.784332  0.856525
16  0.763839  0.939116  0.404821  0.552194
17  0.022347  0.630668  0.489573  0.260511
18  0.627586  0.433779  0.671155  0.532874
19  0.301858  0.298769  0.798762  0.764259
20  0.142179  0.619653  0.323978  0.888950
21  0.926242  0.217204  0.564809  0.028075
22  0.179773  0.788458  0.029599  0.652266
23  0.171783  0.989442  0.937884  0.180094
24  0.208744  0.337994  0.302842  0.238919
25  0.926770  0.309315  0.494531  0.915049
26  0.055591  0.420022  0.188748  0.451578
27  0.632032  0.247067  0.957822  0.189549
28  0.562152  0.734134  0.497345  0.800104
29  0.579877  0.346681  0.854146  0.085848
30  0.211561  0.320044  0.943333  0.316814
31  0.097076  0.280410  0.772864  0.661712
32  0.974969  0.602378  0.940926  0.454194
33  0.423371  0.347027  0.756002  0.665183
34  0.932267  0.107655  0.750186  0.861590
35  0.861419  0.341958  0.370188  0.391162
36  0.473516  0.626241  0.895984  0.664134
37  0.717528  0.035882  0.331638  0.089512
38  0.436924  0.738777  0.235961  0.143661
39  0.419629  0.306565  0.922235  0.689459
40  0.921927  0.906192  0.317434  0.716091
41  0.398761  0.647721  0.184611  0.918044
42  0.265096  0.838655  0.705364  0.363530
43  0.788504  0.101992  0.046296  0.651167
44  0.889600  0.766079  0.661138  0.942407
45  0.810314  0.584719  0.497017  0.393669
46  0.770551  0.655027  0.197000  0.359072
47  0.059326  0.766461  0.077826  0.026166
48  0.321085  0.595879  0.931095  0.170308
49  0.600603  0.321105  0.973736  0.979337

In [7]:
# df.drop(['A'] , axis = 1) # drop vertically
df.drop("B", axis = 1)   # drop vertically

           A         C         D
0   0.957947  0.573323  0.068723
1   0.970251  0.371192  0.984706
2   0.181686  0.775055  0.541684
3   0.282626  0.843035  0.807849
4   0.916001  0.953732  0.327281
5   0.469337  0.187827  0.779300
6   0.723460  0.673378  0.934733
7   0.903760  0.831583  0.015014
8   0.780017  0.139210  0.941163
9   0.074794  0.089173  0.563264
10  0.760997  0.436472  0.794498
11  0.712082  0.151731  0.392466
12  0.718635  0.063989  0.282076
13  0.383215  0.446602  0.630955
14  0.982769  0.403820  0.990278
15  0.982311  0.784332  0.856525
16  0.763839  0.404821  0.552194
17  0.022347  0.489573  0.260511
18  0.627586  0.671155  0.532874
19  0.301858  0.798762  0.764259
20  0.142179  0.323978  0.888950
21  0.926242  0.564809  0.028075
22  0.179773  0.029599  0.652266
23  0.171783  0.937884  0.180094
24  0.208744  0.302842  0.238919
25  0.926770  0.494531  0.915049
26  0.055591  0.188748  0.451578
27  0.632032  0.957822  0.189549
28  0.562152  0.497345  0.800104
29  0.579877  0.854146  0.085848
30  0.211561  0.943333  0.316814
31  0.097076  0.772864  0.661712
32  0.974969  0.940926  0.454194
33  0.423371  0.756002  0.665183
34  0.932267  0.750186  0.861590
35  0.861419  0.370188  0.391162
36  0.473516  0.895984  0.664134
37  0.717528  0.331638  0.089512
38  0.436924  0.235961  0.143661
39  0.419629  0.922235  0.689459
40  0.921927  0.317434  0.716091
41  0.398761  0.184611  0.918044
42  0.265096  0.705364  0.363530
43  0.788504  0.046296  0.651167
44  0.889600  0.661138  0.942407
45  0.810314  0.497017  0.393669
46  0.770551  0.197000  0.359072
47  0.059326  0.077826  0.026166
48  0.321085  0.931095  0.170308
49  0.600603  0.973736  0.979337

In [8]:
  df.drop(columns = ['C'])

           A         B         D
0   0.957947  0.329723  0.068723
1   0.970251  0.534354  0.984706
2   0.181686  0.636601  0.541684
3   0.282626  0.706310  0.807849
4   0.916001  0.870574  0.327281
5   0.469337  0.473610  0.779300
6   0.723460  0.377932  0.934733
7   0.903760  0.229099  0.015014
8   0.780017  0.496608  0.941163
9   0.074794  0.811899  0.563264
10  0.760997  0.869896  0.794498
11  0.712082  0.626183  0.392466
12  0.718635  0.321063  0.282076
13  0.383215  0.847225  0.630955
14  0.982769  0.875104  0.990278
15  0.982311  0.374351  0.856525
16  0.763839  0.939116  0.552194
17  0.022347  0.630668  0.260511
18  0.627586  0.433779  0.532874
19  0.301858  0.298769  0.764259
20  0.142179  0.619653  0.888950
21  0.926242  0.217204  0.028075
22  0.179773  0.788458  0.652266
23  0.171783  0.989442  0.180094
24  0.208744  0.337994  0.238919
25  0.926770  0.309315  0.915049
26  0.055591  0.420022  0.451578
27  0.632032  0.247067  0.189549
28  0.562152  0.734134  0.800104
29  0.579877  0.346681  0.085848
30  0.211561  0.320044  0.316814
31  0.097076  0.280410  0.661712
32  0.974969  0.602378  0.454194
33  0.423371  0.347027  0.665183
34  0.932267  0.107655  0.861590
35  0.861419  0.341958  0.391162
36  0.473516  0.626241  0.664134
37  0.717528  0.035882  0.089512
38  0.436924  0.738777  0.143661
39  0.419629  0.306565  0.689459
40  0.921927  0.906192  0.716091
41  0.398761  0.647721  0.918044
42  0.265096  0.838655  0.363530
43  0.788504  0.101992  0.651167
44  0.889600  0.766079  0.942407
45  0.810314  0.584719  0.393669
46  0.770551  0.655027  0.359072
47  0.059326  0.766461  0.026166
48  0.321085  0.595879  0.170308
49  0.600603  0.321105  0.979337

In [9]:
df1 = df

In [10]:
df1.drop(2 , axis = 0)

           A         B         C         D
0   0.957947  0.329723  0.573323  0.068723
1   0.970251  0.534354  0.371192  0.984706
3   0.282626  0.706310  0.843035  0.807849
4   0.916001  0.870574  0.953732  0.327281
5   0.469337  0.473610  0.187827  0.779300
6   0.723460  0.377932  0.673378  0.934733
7   0.903760  0.229099  0.831583  0.015014
8   0.780017  0.496608  0.139210  0.941163
9   0.074794  0.811899  0.089173  0.563264
10  0.760997  0.869896  0.436472  0.794498
11  0.712082  0.626183  0.151731  0.392466
12  0.718635  0.321063  0.063989  0.282076
13  0.383215  0.847225  0.446602  0.630955
14  0.982769  0.875104  0.403820  0.990278
15  0.982311  0.374351  0.784332  0.856525
16  0.763839  0.939116  0.404821  0.552194
17  0.022347  0.630668  0.489573  0.260511
18  0.627586  0.433779  0.671155  0.532874
19  0.301858  0.298769  0.798762  0.764259
20  0.142179  0.619653  0.323978  0.888950
21  0.926242  0.217204  0.564809  0.028075
22  0.179773  0.788458  0.029599  0.652266
23  0.171783  0.989442  0.937884  0.180094
24  0.208744  0.337994  0.302842  0.238919
25  0.926770  0.309315  0.494531  0.915049
26  0.055591  0.420022  0.188748  0.451578
27  0.632032  0.247067  0.957822  0.189549
28  0.562152  0.734134  0.497345  0.800104
29  0.579877  0.346681  0.854146  0.085848
30  0.211561  0.320044  0.943333  0.316814
31  0.097076  0.280410  0.772864  0.661712
32  0.974969  0.602378  0.940926  0.454194
33  0.423371  0.347027  0.756002  0.665183
34  0.932267  0.107655  0.750186  0.861590
35  0.861419  0.341958  0.370188  0.391162
36  0.473516  0.626241  0.895984  0.664134
37  0.717528  0.035882  0.331638  0.089512
38  0.436924  0.738777  0.235961  0.143661
39  0.419629  0.306565  0.922235  0.689459
40  0.921927  0.906192  0.317434  0.716091
41  0.398761  0.647721  0.184611  0.918044
42  0.265096  0.838655  0.705364  0.363530
43  0.788504  0.101992  0.046296  0.651167
44  0.889600  0.766079  0.661138  0.942407
45  0.810314  0.584719  0.497017  0.393669
46  0.770551  0.655027  0.197000  0.359072
47  0.059326  0.766461  0.077826  0.026166
48  0.321085  0.595879  0.931095  0.170308
49  0.600603  0.321105  0.973736  0.979337

In [11]:
df1.drop(4 , axis = 0)

           A         B         C         D
0   0.957947  0.329723  0.573323  0.068723
1   0.970251  0.534354  0.371192  0.984706
2   0.181686  0.636601  0.775055  0.541684
3   0.282626  0.706310  0.843035  0.807849
5   0.469337  0.473610  0.187827  0.779300
6   0.723460  0.377932  0.673378  0.934733
7   0.903760  0.229099  0.831583  0.015014
8   0.780017  0.496608  0.139210  0.941163
9   0.074794  0.811899  0.089173  0.563264
10  0.760997  0.869896  0.436472  0.794498
11  0.712082  0.626183  0.151731  0.392466
12  0.718635  0.321063  0.063989  0.282076
13  0.383215  0.847225  0.446602  0.630955
14  0.982769  0.875104  0.403820  0.990278
15  0.982311  0.374351  0.784332  0.856525
16  0.763839  0.939116  0.404821  0.552194
17  0.022347  0.630668  0.489573  0.260511
18  0.627586  0.433779  0.671155  0.532874
19  0.301858  0.298769  0.798762  0.764259
20  0.142179  0.619653  0.323978  0.888950
21  0.926242  0.217204  0.564809  0.028075
22  0.179773  0.788458  0.029599  0.652266
23  0.171783  0.989442  0.937884  0.180094
24  0.208744  0.337994  0.302842  0.238919
25  0.926770  0.309315  0.494531  0.915049
26  0.055591  0.420022  0.188748  0.451578
27  0.632032  0.247067  0.957822  0.189549
28  0.562152  0.734134  0.497345  0.800104
29  0.579877  0.346681  0.854146  0.085848
30  0.211561  0.320044  0.943333  0.316814
31  0.097076  0.280410  0.772864  0.661712
32  0.974969  0.602378  0.940926  0.454194
33  0.423371  0.347027  0.756002  0.665183
34  0.932267  0.107655  0.750186  0.861590
35  0.861419  0.341958  0.370188  0.391162
36  0.473516  0.626241  0.895984  0.664134
37  0.717528  0.035882  0.331638  0.089512
38  0.436924  0.738777  0.235961  0.143661
39  0.419629  0.306565  0.922235  0.689459
40  0.921927  0.906192  0.317434  0.716091
41  0.398761  0.647721  0.184611  0.918044
42  0.265096  0.838655  0.705364  0.363530
43  0.788504  0.101992  0.046296  0.651167
44  0.889600  0.766079  0.661138  0.942407
45  0.810314  0.584719  0.497017  0.393669
46  0.770551  0.655027  0.197000  0.359072
47  0.059326  0.766461  0.077826  0.026166
48  0.321085  0.595879  0.931095  0.170308
49  0.600603  0.321105  0.973736  0.979337

In [12]:
df1.reset_index(drop = True , inplace = True)

In [13]:
df1['E'] = None

In [14]:
df1

           A         B         C         D     E
0   0.957947  0.329723  0.573323  0.068723  None
1   0.970251  0.534354  0.371192  0.984706  None
2   0.181686  0.636601  0.775055  0.541684  None
3   0.282626  0.706310  0.843035  0.807849  None
4   0.916001  0.870574  0.953732  0.327281  None
5   0.469337  0.473610  0.187827  0.779300  None
6   0.723460  0.377932  0.673378  0.934733  None
7   0.903760  0.229099  0.831583  0.015014  None
8   0.780017  0.496608  0.139210  0.941163  None
9   0.074794  0.811899  0.089173  0.563264  None
10  0.760997  0.869896  0.436472  0.794498  None
11  0.712082  0.626183  0.151731  0.392466  None
12  0.718635  0.321063  0.063989  0.282076  None
13  0.383215  0.847225  0.446602  0.630955  None
14  0.982769  0.875104  0.403820  0.990278  None
15  0.982311  0.374351  0.784332  0.856525  None
16  0.763839  0.939116  0.404821  0.552194  None
17  0.022347  0.630668  0.489573  0.260511  None
18  0.627586  0.433779  0.671155  0.532874  None
19  0.301858  0.298769  0.798762  0.764259  None
20  0.142179  0.619653  0.323978  0.888950  None
21  0.926242  0.217204  0.564809  0.028075  None
22  0.179773  0.788458  0.029599  0.652266  None
23  0.171783  0.989442  0.937884  0.180094  None
24  0.208744  0.337994  0.302842  0.238919  None
25  0.926770  0.309315  0.494531  0.915049  None
26  0.055591  0.420022  0.188748  0.451578  None
27  0.632032  0.247067  0.957822  0.189549  None
28  0.562152  0.734134  0.497345  0.800104  None
29  0.579877  0.346681  0.854146  0.085848  None
30  0.211561  0.320044  0.943333  0.316814  None
31  0.097076  0.280410  0.772864  0.661712  None
32  0.974969  0.602378  0.940926  0.454194  None
33  0.423371  0.347027  0.756002  0.665183  None
34  0.932267  0.107655  0.750186  0.861590  None
35  0.861419  0.341958  0.370188  0.391162  None
36  0.473516  0.626241  0.895984  0.664134  None
37  0.717528  0.035882  0.331638  0.089512  None
38  0.436924  0.738777  0.235961  0.143661  None
39  0.419629  0.306565  0.922235  0.689459  None
40  0.921927  0.906192  0.317434  0.716091  None
41  0.398761  0.647721  0.184611  0.918044  None
42  0.265096  0.838655  0.705364  0.363530  None
43  0.788504  0.101992  0.046296  0.651167  None
44  0.889600  0.766079  0.661138  0.942407  None
45  0.810314  0.584719  0.497017  0.393669  None
46  0.770551  0.655027  0.197000  0.359072  None
47  0.059326  0.766461  0.077826  0.026166  None
48  0.321085  0.595879  0.931095  0.170308  None
49  0.600603  0.321105  0.973736  0.979337  None

In [15]:
# isnull()

df1.isnull()

        A      B      C      D     E
0   False  False  False  False  True
1   False  False  False  False  True
2   False  False  False  False  True
3   False  False  False  False  True
4   False  False  False  False  True
5   False  False  False  False  True
6   False  False  False  False  True
7   False  False  False  False  True
8   False  False  False  False  True
9   False  False  False  False  True
10  False  False  False  False  True
11  False  False  False  False  True
12  False  False  False  False  True
13  False  False  False  False  True
14  False  False  False  False  True
15  False  False  False  False  True
16  False  False  False  False  True
17  False  False  False  False  True
18  False  False  False  False  True
19  False  False  False  False  True
20  False  False  False  False  True
21  False  False  False  False  True
22  False  False  False  False  True
23  False  False  False  False  True
24  False  False  False  False  True
25  False  False  False  False  True
26  False  False  False  False  True
27  False  False  False  False  True
28  False  False  False  False  True
29  False  False  False  False  True
30  False  False  False  False  True
31  False  False  False  False  True
32  False  False  False  False  True
33  False  False  False  False  True
34  False  False  False  False  True
35  False  False  False  False  True
36  False  False  False  False  True
37  False  False  False  False  True
38  False  False  False  False  True
39  False  False  False  False  True
40  False  False  False  False  True
41  False  False  False  False  True
42  False  False  False  False  True
43  False  False  False  False  True
44  False  False  False  False  True
45  False  False  False  False  True
46  False  False  False  False  True
47  False  False  False  False  True
48  False  False  False  False  True
49  False  False  False  False  True

In [16]:
# df1['E'] = 90

In [18]:
df1.isnull().sum()

A     0
B     0
C     0
D     0
E    50
dtype: int64

In [22]:
df2 = df1.drop('B' , axis = 1)

In [23]:
df2

           A         C         D     E
0   0.957947  0.573323  0.068723  None
1   0.970251  0.371192  0.984706  None
2   0.181686  0.775055  0.541684  None
3   0.282626  0.843035  0.807849  None
4   0.916001  0.953732  0.327281  None
5   0.469337  0.187827  0.779300  None
6   0.723460  0.673378  0.934733  None
7   0.903760  0.831583  0.015014  None
8   0.780017  0.139210  0.941163  None
9   0.074794  0.089173  0.563264  None
10  0.760997  0.436472  0.794498  None
11  0.712082  0.151731  0.392466  None
12  0.718635  0.063989  0.282076  None
13  0.383215  0.446602  0.630955  None
14  0.982769  0.403820  0.990278  None
15  0.982311  0.784332  0.856525  None
16  0.763839  0.404821  0.552194  None
17  0.022347  0.489573  0.260511  None
18  0.627586  0.671155  0.532874  None
19  0.301858  0.798762  0.764259  None
20  0.142179  0.323978  0.888950  None
21  0.926242  0.564809  0.028075  None
22  0.179773  0.029599  0.652266  None
23  0.171783  0.937884  0.180094  None
24  0.208744  0.302842  0.238919  None
25  0.926770  0.494531  0.915049  None
26  0.055591  0.188748  0.451578  None
27  0.632032  0.957822  0.189549  None
28  0.562152  0.497345  0.800104  None
29  0.579877  0.854146  0.085848  None
30  0.211561  0.943333  0.316814  None
31  0.097076  0.772864  0.661712  None
32  0.974969  0.940926  0.454194  None
33  0.423371  0.756002  0.665183  None
34  0.932267  0.750186  0.861590  None
35  0.861419  0.370188  0.391162  None
36  0.473516  0.895984  0.664134  None
37  0.717528  0.331638  0.089512  None
38  0.436924  0.235961  0.143661  None
39  0.419629  0.922235  0.689459  None
40  0.921927  0.317434  0.716091  None
41  0.398761  0.184611  0.918044  None
42  0.265096  0.705364  0.363530  None
43  0.788504  0.046296  0.651167  None
44  0.889600  0.661138  0.942407  None
45  0.810314  0.497017  0.393669  None
46  0.770551  0.197000  0.359072  None
47  0.059326  0.077826  0.026166  None
48  0.321085  0.931095  0.170308  None
49  0.600603  0.973736  0.979337  None

In [26]:
df3 = pd.DataFrame(
    {
        "name" : ['sam' , 'Rohit' , 'kirti' , 'Shubhum', 'Purvi'] , 
        "Grade" : ['A','B','A','B','A'],
        "Marks" : [89,65,70,50,77],
        "FullMarks" : [300,250,330,350,389] 
    }
)

In [27]:
df3

      name Grade  Marks  FullMarks
0      sam     A     89        300
1    Rohit     B     65        250
2    kirti     A     70        330
3  Shubhum     B     50        350
4    Purvi     A     77        389

In [30]:
df3['Pass'] = df3['name'].where(df3['FullMarks']>250 , other = 0)

In [31]:
df3

      name Grade  Marks  FullMarks     Pass
0      sam     A     89        300      sam
1    Rohit     B     65        250        0
2    kirti     A     70        330    kirti
3  Shubhum     B     50        350  Shubhum
4    Purvi     A     77        389    Purvi

In [42]:
df3['Result'] = df3['name'].where(df3['FullMarks']>300 , other = 'Fail')

In [43]:
df3

      name Grade  Marks  FullMarks     Pass   Result
0      sam     A     89        300      sam     Fail
1    Rohit     B     65        250        0     Fail
2    kirti     A     70        330    kirti    kirti
3  Shubhum     B     50        350  Shubhum  Shubhum
4    Purvi     A     77        389    Purvi    Purvi